CREATE ROLE spvchannels LOGIN
  PASSWORD 'WR6NUJEyG-kYMKz9Z6Y9^%^SP^3kuX'
  NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION;

 GRANT ALL PRIVILEGES ON DATABASE spvchannels TO spvchannels;
  
 GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO spvchannels;
 GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO spvchannels;